### ISSUE TITLE
EDIT and UPDATE confusion

### ISSUE THREAD

**Issue by safuya** [learn-co-curriculum/sinatra-restful-routes-readme#36]
Reading at various other places on the Internet, it seems like the edit should be the form for editing, and the update should just be the patch/put to send the update to the model. Should the table be updated to the below?

| HTTP Verb | ROUTE             | Action | Used For                                         |
|-----------|-------------------|--------|--------------------------------------------------|
| GET       | /posts            | index  | Index page to display all posts                  |
| GET       | /posts/new        | new    | Displays create form post                        |
| POST      | /posts            | create | Creates one blog post                            |
| GET       | /posts/:id        | show   | Display one blog post based on the ID in the url |
| GET       | /posts/:id/edit   | edit   | Display edit form for the ID in the url          |
| PATCH     | /posts/:id        | update | Updates the blog post for the ID in the url      |
| DELETE    | /posts/:id/delete | delete | Delete the blog post for the ID in the url       |

**Comment by mjhough** [comment]
@DanielSeehausen @sgharms

**Comment by kkterai** [comment]
@DanielSeehausen @sgharms @safuya The original table looks correct around PUT and PATCH: PUT will replace a record while PATCH will update only the diff

https://stackoverflow.com/questions/21660791/what-is-the-main-difference-between-patch-and-put-request

https://datatracker.ietf.org/doc/rfc5789/

However, it does seem redundant to have both a 
GET | '/posts/:id/edit' | edit action | displays edit form based on ID in the url
and
GET | '/posts/:id/update' | update action | displays update form blog post based on ID in the url

I can't find a reason to keep both (preferring the /posts/:id/edit)

**Comment by sgharms** [comment]
@kkterai

I think there's a couple of very subtle things going on here.

The "Special Verb" methods are PUT/PATCH/DELETE.

1. In `master` it says:

`GET' /posts/:id/update'	update action	displays update form blog post based on ID in the url`

What's the point of this route? As a GET I expect an idempotent fetch of data.
The description says "displays update form" ...._but what's the difference
between_ this and the `edit` action? None as far as I can tell, I think that
row should be deleted.

2. If we remove that, then the bottom of the chart is:

|verb|path|
|----|-----|
| PUT | ... |
| PATCH | ... |
| DELETE | ... |

Now, I would expect all of those routes to point to the exact same path. Rails,
for reference says that these three verbs all point to the [same path](http://guides.rubyonrails.org/routing.html#crud-verbs-and-actions)

3. In the `PATCH` line we use the verb `edits` which I think is
confusing since `edit` is also a route type. I think our verb there should be
`modifies the Post by applying the smallest amount of changes``

4. In the `PUT` ine we might adjust the statement to: `replaces an existing
blog post based on ID in the url; preserves the `id` but expects to update
every single field in the Post's database row.

I've proposed a fix in #37.

Could you double-check my logic there and make sure I'm not running afoul of
Sinatra conventions?

Steven

**Comment by realAndrewCohn** [comment]
fixed by cbaa2ef9858b839c9111eb381d1b5196ea95157b
